export const RESEARCH_REPORT_SOURCES = [
  {
    id: 'eastmoney-report-center',
    title: '东方财富研报中心',
    url: 'https://emdata.eastmoney.com/ybzx/index.html',
    category: 'eastmoney',
    sourceLabel: '东方财富',
    tags: ['自动抓取', '聚合页', '东财'],
  },
  {
    id: 'eastmoney-stock-report',
    title: '东方财富个股研报页',
    url: 'https://data.eastmoney.com/report/stock.jshtml',
    category: 'eastmoney',
    sourceLabel: '东方财富',
    tags: ['自动抓取', '个股', '东财'],
  },
  {
    id: 'eastmoney-industry-report',
    title: '东方财富行业研报页',
    url: 'https://data.eastmoney.com/report/industry.jshtml',
    category: 'eastmoney',
    sourceLabel: '东方财富',
    tags: ['自动抓取', '行业', '东财'],
  },
  {
    id: 'eastmoney-strategy-report',
    title: '东方财富策略报告页',
    url: 'https://data.eastmoney.com/report/strategyreport.jshtml',
    category: 'eastmoney',
    sourceLabel: '东方财富',
    tags: ['自动抓取', '策略', '东财'],
  },
  {
    id: 'eastmoney-macro-report',
    title: '东方财富宏观研究页',
    url: 'https://data.eastmoney.com/report/macresearch.jshtml',
    category: 'eastmoney',
    sourceLabel: '东方财富',
    tags: ['自动抓取', '宏观', '东财'],
  },
  {
    id: 'tfzq-research-business',
    title: '天风证券研究业务页',
    url: 'https://www.tfzq.com/about/ywjsyjyw.html',
    category: 'brokers/tfzq',
    sourceLabel: '天风证券',
    tags: ['自动抓取', '券商', '天风证券'],
  },
  {
    id: 'tfzq-research-authorization',
    title: '天风证券研报转载授权声明',
    url: 'https://www.tfzq.com/8960378933631516929.html',
    category: 'brokers/tfzq',
    sourceLabel: '天风证券',
    tags: ['自动抓取', '券商', '授权声明', '天风证券'],
  },
];
